### ISSUE TITLE
Found the Bug as you see

### ISSUE THREAD

**Issue by ski043** [AntonBritva92/blog-next#1]
Soo pushed the code and as you see it now works. The link was not linking correctly you used () but it should be {}. 

Also I added export const revalidate = 60; // revalidate this page every 60 seconds

You have to do this because with server components by default, the response gets cached forever. So what you have to do is add a revalidate tag.

This tells vercel to revalidate the page every 60 seconds. This would mean the first request would be fresh, then all subsequent requests would get cached data for 60 seconds, and after 60 seconds, the first request would again revalidate the fetch and show updates.

You can change the revalidation seconds to whatever you want.

If you want to deploy sanity do the following: 
cd into your sanity folder
and run npm run deploy

Also you can close this issue, only opend it so you can see my message ✌🏻

**Comment by AntonBritva92** [comment]
I'm in shock, thank you! I struggled for a whole week, read the
documentation, tried to understand what the problem was...

Thank you once again for not killing at the request and helping!

Your videos are very cool and informative! I wish success to your channel
and career!

пт, 28 лип. 2023 р. о 20:38 Jan ***@***.***> пише:
